services:
  - type: web
    name: agent-server
    env: python
    buildCommand: ./build.sh && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false


# services:
#   - type: web
#     name: media-agent
#     env: docker
#     plan: free
#     autoDeploy: true
#     healthCheckPath: /health
#     envVars:
#       - key: PORT
#         value: 10000

